[project]
name = "sfm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jinja2>=3.1.6",
    "pyperclip>=1.9.0",
]

[dependency-groups]
dev = [
    "pyright>=1.1.403",
]
